/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OptinRouteImport } from './routes/optin'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCalSlotsRouteImport } from './routes/api/public/cal/slots'
import { Route as ApiPublicCalBookingRouteImport } from './routes/api/public/cal/booking'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OptinRoute = OptinRouteImport.update({
  id: '/optin',
  path: '/optin',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalSlotsRoute = ApiPublicCalSlotsRouteImport.update({
  id: '/api/public/cal/slots',
  path: '/api/public/cal/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalBookingRoute = ApiPublicCalBookingRouteImport.update({
  id: '/api/public/cal/booking',
  path: '/api/public/cal/booking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/optin': typeof OptinRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/api/public/cal/booking': typeof ApiPublicCalBookingRoute
  '/api/public/cal/slots': typeof ApiPublicCalSlotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/optin': typeof OptinRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/api/public/cal/booking': typeof ApiPublicCalBookingRoute
  '/api/public/cal/slots': typeof ApiPublicCalSlotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/optin': typeof OptinRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/api/public/cal/booking': typeof ApiPublicCalBookingRoute
  '/api/public/cal/slots': typeof ApiPublicCalSlotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/cookie-policy'
    | '/optin'
    | '/privacy'
    | '/quiz'
    | '/api/public/cal/booking'
    | '/api/public/cal/slots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/cookie-policy'
    | '/optin'
    | '/privacy'
    | '/quiz'
    | '/api/public/cal/booking'
    | '/api/public/cal/slots'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/cookie-policy'
    | '/optin'
    | '/privacy'
    | '/quiz'
    | '/api/public/cal/booking'
    | '/api/public/cal/slots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  OptinRoute: typeof OptinRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  ApiPublicCalBookingRoute: typeof ApiPublicCalBookingRoute
  ApiPublicCalSlotsRoute: typeof ApiPublicCalSlotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optin': {
      id: '/optin'
      path: '/optin'
      fullPath: '/optin'
      preLoaderRoute: typeof OptinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cal/slots': {
      id: '/api/public/cal/slots'
      path: '/api/public/cal/slots'
      fullPath: '/api/public/cal/slots'
      preLoaderRoute: typeof ApiPublicCalSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cal/booking': {
      id: '/api/public/cal/booking'
      path: '/api/public/cal/booking'
      fullPath: '/api/public/cal/booking'
      preLoaderRoute: typeof ApiPublicCalBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  OptinRoute: OptinRoute,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  ApiPublicCalBookingRoute: ApiPublicCalBookingRoute,
  ApiPublicCalSlotsRoute: ApiPublicCalSlotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
